triggers = [
    "Booking Canceled",
    "Booking Created",
    "Booking Rejected",
    "Booking Requested",
    "Booking Payment Initiated",
    "Booking Rescheduled",
    "Booking Paid",
    "Booking No-Show Updated",
    "Meeting Ended",
    "Meeting Started",
    "Recording Download Link Ready",
    "Instant Meeting Created",
    "Out of Office Created",
    "Transcript Generated",
    "After hosts didn't join cal video",
    "After guests didn't join cal video",
    "Form Submitted",
    "Form submitted, no event booked",
]
