BOOKING_TRIGGERS = {
    "BOOKING_CANCELLED": "Booking Cancelled",
    "BOOKING_CREATED": "Booking Created",
    "BOOKING_REJECTED": "Booking Rejected",
    "BOOKING_REQUESTED": "Booking Requested",
    "BOOKING_PAYMENT_INITIATED": "Booking Payment Initiated",
    "BOOKING_RESCHEDULED": "Booking Rescheduled",
    "BOOKING_PAID": "Booking Paid",
    "BOOKING_NO-SHOW_UPDATED": "Booking No-Show Updated",
    "MEETING_ENDED": "Meeting Ended",
    "MEETING_STARTED": "Meeting Started",
    "RECORDING_DOWNLOAD_LINK READY": "Recording Download Link Ready",
    "INSTANT_MEETING_CREATED": "Instant Meeting Created",
    "OUT_OF_OFFICE_CREATED": "Out of Office Created",
    "TRANSCRIPT_GENERATED": "Transcript Generated",
    "AFTER_HOSTS_DIDN'T_JOIN_CAL_VIDEO": "After hosts didn't join cal video",
    "AFTER_GUESTS_DIDN'T_JOIN_CAL_VIDEO": "After guests didn't join cal video",
    "FORM_SUBMITTED": "Form Submitted",
    "FORM_SUBMITTED,_NO_EVENT_BOOKED": "Form submitted, no event booked",
}
